language: node_js
node_js:
  - "10.16"

script:
  - npm run lint
  - npm run test
  - npm run coverage

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
     tags: true 